[project]
name = "language-learning-nkl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edge-tts>=7.2.3",
    "faster-whisper>=1.2.0",
]
